name: flutter_iot_energy
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_database: ^10.1.2
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.0
  gradient_borders: ^1.0.0
  intl_phone_field: ^3.1.0
  pull_to_refresh: ^2.0.0
  responsive_sizer: ^3.1.1
  url_launcher: ^6.1.11
  flutter: 
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^5.0.0+1
  flutter_lints: ^2.0.2
  flutter_test: 
    sdk: flutter
flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icons/iot_energy_icon.png
  image_path_android: assets/icons/iot_energy_icon.png
  adaptive_icon_background: assets/icons/iot_energy_icon_background.png
  adaptive_icon_foreground: assets/icons/iot_energy_icon_foreground.png
  ios: true
  min_sdk_android: 21
flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
